/**
 * CHARACTERIZATION, captured before #1695 changes anything: the exact bytes
 * every unnamed merge produces today, for a first run and a re-run, with and
 * without sibling entries. #1695 parametrizes the writers on a server-name
 * pair; the owner decision on epic #1694 is that the UNNAMED path stays
 * byte-identical — every currently-wired host keeps working untouched.
 * Every string below was generated by running the pre-#1695 functions.
 */
import { describe, it, expect } from 'vitest'
import {
  mergeCodexToml,
  mergeCodexTomlHosted,
  mergeHermesEnv,
  mergeHermesYaml,
  mergeJsonMcpConfig,
} from './config-writers.js'

const HOSTED = { url: 'https://mcp.haven.example/mcp', headers: { Authorization: 'Bearer sk_agent_key' } }
const SIGNER = { command: '/home/u/.haven/agents/a/bin/haven-signer.mjs', args: [] as string[] }

const JSON_FIRST =
  '{\n  "mcpServers": {\n    "haven": {\n      "url": "https://mcp.haven.example/mcp",\n      "headers": {\n        "Authorization": "Bearer sk_agent_key"\n      }\n    },\n    "haven-signer": {\n      "command": "/home/u/.haven/agents/a/bin/haven-signer.mjs",\n      "args": []\n    }\n  }\n}\n'

const JSON_WITH_SIBLING =
  '{\n  "mcpServers": {\n    "other": {\n      "url": "https://x"\n    },\n    "haven": {\n      "url": "https://mcp.haven.example/mcp",\n      "headers": {\n        "Authorization": "Bearer sk_agent_key"\n      }\n    },\n    "haven-signer": {\n      "command": "/home/u/.haven/agents/a/bin/haven-signer.mjs",\n      "args": []\n    }\n  }\n}\n'

const YAML_FIRST =
  'mcp_servers:\n  haven:\n    url: https://mcp.haven.example/mcp\n    headers:\n      Authorization: Bearer sk_agent_key\n    enabled: true\n  haven-signer:\n    command: /home/u/.haven/agents/a/bin/haven-signer.mjs\n    args: []\n    enabled: true\n'

// Pre-#1695 quirk, pinned deliberately: the re-run loses the trailing newline.
const YAML_RERUN = YAML_FIRST.trimEnd()

const TOML_FIRST =
  '[mcp_servers.haven]\nurl = "https://mcp.haven.example/mcp"\nhttp_headers = { "Authorization" = "Bearer sk_agent_key" }\n\n[mcp_servers.haven_signer]\ncommand = "/home/u/.haven/agents/a/bin/haven-signer.mjs"\nargs = []\nstartup_timeout_sec = 120\n'

const TOML_WITH_SIBLING =
  '[mcp_servers.other]\nurl = "https://x"\n\n' + TOML_FIRST

const TOML_LOCAL =
  '[mcp_servers.haven]\ncommand = "/usr/local/bin/haven-mcp"\nargs = []\nstartup_timeout_sec = 120\n'

describe('pre-#1695 characterization: the unnamed path is byte-identical', () => {
  it('JSON runtimes: first run, re-run, and sibling preservation', () => {
    const first = mergeJsonMcpConfig(null, 'mcpServers', HOSTED, SIGNER)
    expect(first).toBe(JSON_FIRST)
    expect(mergeJsonMcpConfig(first, 'mcpServers', HOSTED, SIGNER)).toBe(JSON_FIRST)
    const sibling = JSON.stringify({ mcpServers: { other: { url: 'https://x' } } }, null, 2)
    expect(mergeJsonMcpConfig(sibling, 'mcpServers', HOSTED, SIGNER)).toBe(JSON_WITH_SIBLING)
  })

  it('Hermes YAML: first run and re-run', () => {
    const hosted = { ...HOSTED, enabled: true }
    const signer = { ...SIGNER, enabled: true }
    const first = mergeHermesYaml(null, hosted, signer)
    expect(first).toBe(YAML_FIRST)
    expect(mergeHermesYaml(first, hosted, signer)).toBe(YAML_RERUN)
  })

  it('Hermes env: first run and upsert among unrelated keys', () => {
    expect(mergeHermesEnv(null, 'sk_agent_key')).toBe('MCP_HAVEN_API_KEY=sk_agent_key\n')
    expect(mergeHermesEnv('MCP_HAVEN_API_KEY=old\nOTHER=1\n', 'sk_agent_key')).toBe(
      'MCP_HAVEN_API_KEY=sk_agent_key\nOTHER=1\n',
    )
  })

  it('Codex TOML hosted: first run, re-run, and sibling preservation', () => {
    const first = mergeCodexTomlHosted('', 'https://mcp.haven.example/mcp', 'sk_agent_key', SIGNER)
    expect(first).toBe(TOML_FIRST)
    expect(mergeCodexTomlHosted(first, 'https://mcp.haven.example/mcp', 'sk_agent_key', SIGNER)).toBe(TOML_FIRST)
    expect(
      mergeCodexTomlHosted('[mcp_servers.other]\nurl = "https://x"\n', 'https://mcp.haven.example/mcp', 'sk_agent_key', SIGNER),
    ).toBe(TOML_WITH_SIBLING)
  })

  it('Codex TOML local: first run', () => {
    expect(mergeCodexToml('', '/usr/local/bin/haven-mcp')).toBe(TOML_LOCAL)
  })
})
