/**
 * GENERATED by `scripts/release-bump.mjs` from the five package CHANGELOGs
 * (#3305, via `scripts/release-client-data.mjs`). Do not hand-edit: the bump
 * regenerates this file from the CHANGELOGs before every release and REFUSES
 * to run when the file on disk differs from what they produce.
 *
 * To change a note, change the CHANGELOG entry it comes from. To mark a
 * release as one clients must update to, put `**Update required**` on its
 * CHANGELOG bullet. The enforced thresholds are NOT here — they live in
 * `client-compat.ts`, which the bump never writes.
 *
 * Untyped on purpose: `client-releases.ts` imports this and types it, so
 * this file imports nothing and no module cycle forms.
 */

export const CLIENT_RELEASE_DATA = {
  "@haven_ai/sdk": {
    "released_version": "0.9.0-alpha.0",
    "notes": [
      {
        "version": "0.9.0-alpha.0",
        "date": "2026-10-09",
        "summary": "The SDK reports the merchant's EIP-3009 settlement hash it already holds. (+11 more in the changelog)",
        "summary_segments": [
          {
            "text": "The SDK reports the merchant's EIP-3009 settlement hash it already holds. (+11 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      },
      {
        "version": "0.8.1-alpha.0",
        "date": "2026-10-07",
        "summary": "The setup prompt's command-modification rule permits a third change: the re-run a wiring_collision refusal asks for. (+1 more in the changelog)",
        "summary_segments": [
          {
            "text": "The setup prompt's command-modification rule permits a third change: the re-run a ",
            "code": false
          },
          {
            "text": "wiring_collision",
            "code": true
          },
          {
            "text": " refusal asks for. (+1 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      }
    ]
  },
  "@haven_ai/signer": {
    "released_version": "0.9.0-alpha.0",
    "notes": [
      {
        "version": "0.9.0-alpha.0",
        "date": "2026-10-09",
        "summary": "The initialize instructions state the signer's identity and the several-pairs rule. (+5 more in the changelog)",
        "summary_segments": [
          {
            "text": "The ",
            "code": false
          },
          {
            "text": "initialize",
            "code": true
          },
          {
            "text": " instructions state the signer's identity and the several-pairs rule. (+5 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      },
      {
        "version": "0.8.1-alpha.0",
        "date": "2026-10-07",
        "summary": "README: the network-calls section names every sign-context read.",
        "summary_segments": [
          {
            "text": "README: the network-calls section names every sign-context read.",
            "code": false
          }
        ],
        "action_required": false
      }
    ]
  },
  "@haven_ai/mcp": {
    "released_version": "0.9.0-alpha.0",
    "notes": [
      {
        "version": "0.9.0-alpha.0",
        "date": "2026-10-09",
        "summary": "The local x402 tools report the merchant's EIP-3009 settlement hash. (+3 more in the changelog)",
        "summary_segments": [
          {
            "text": "The local x402 tools report the merchant's EIP-3009 settlement hash. (+3 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      },
      {
        "version": "0.8.1-alpha.0",
        "date": "2026-10-07",
        "summary": "No changes to this package in this release.",
        "summary_segments": [
          {
            "text": "No changes to this package in this release.",
            "code": false
          }
        ],
        "action_required": false
      }
    ]
  },
  "@haven_ai/connect": {
    "released_version": "0.9.0-alpha.0",
    "notes": [
      {
        "version": "0.9.0-alpha.0",
        "date": "2026-10-09",
        "summary": "A rebind or --replace now warns that an open session keeps acting as the previous agent. The connector re-points the MCP server name on disk, but a client that is already running keeps the entries it loaded at start-up, and Connect revokes nothing in Haven. (+7 more in the changelog)",
        "summary_segments": [
          {
            "text": "A rebind or ",
            "code": false
          },
          {
            "text": "--replace",
            "code": true
          },
          {
            "text": " now warns that an open session keeps acting as the previous agent. The connector re-points the MCP server name on disk, but a client that is already running keeps the entries it loaded at start-up, and Connect revokes nothing in Haven. (+7 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      },
      {
        "version": "0.8.1-alpha.0",
        "date": "2026-10-07",
        "summary": "README: the wiring_collision relay names the re-run the setup prompt now permits. After the user answers the relay, the dashboard's setup prompt lets an agent re-run once with the flag the user chose (--name or --replace).",
        "summary_segments": [
          {
            "text": "README: the ",
            "code": false
          },
          {
            "text": "wiring_collision",
            "code": true
          },
          {
            "text": " relay names the re-run the setup prompt now permits. After the user answers the relay, the dashboard's setup prompt lets an agent re-run once with the flag the user chose (",
            "code": false
          },
          {
            "text": "--name",
            "code": true
          },
          {
            "text": " or ",
            "code": false
          },
          {
            "text": "--replace",
            "code": true
          },
          {
            "text": ").",
            "code": false
          }
        ],
        "action_required": false
      }
    ]
  },
  "@haven_ai/cli": {
    "released_version": "0.9.0-alpha.0",
    "notes": [
      {
        "version": "0.9.0-alpha.0",
        "date": "2026-10-09",
        "summary": "agents pause, resume and revoke say what they do not do. The help said pause would \"Stop the agent spending\" and revoke would \"Permanently revoke an agent\"; all three are backend-only status changes, and the budget stays live on-chain. (+2 more in the changelog)",
        "summary_segments": [
          {
            "text": "agents pause",
            "code": true
          },
          {
            "text": ", ",
            "code": false
          },
          {
            "text": "resume",
            "code": true
          },
          {
            "text": " and ",
            "code": false
          },
          {
            "text": "revoke",
            "code": true
          },
          {
            "text": " say what they do not do. The help said pause would \"Stop the agent spending\" and revoke would \"Permanently revoke an agent\"; all three are backend-only status changes, and the budget stays live on-chain. (+2 more in the changelog)",
            "code": false
          }
        ],
        "action_required": false
      },
      {
        "version": "0.8.1-alpha.0",
        "date": "2026-10-07",
        "summary": "haven feedback submit \"<text>\". A one-way feedback/bug-report channel to Haven for a signed-in user and the agent working in their terminal — needs haven login, 4000 characters (code points) or fewer, several unquoted words are joined into one text like contacts add's own free-text argument.",
        "summary_segments": [
          {
            "text": "haven feedback submit \"<text>\"",
            "code": true
          },
          {
            "text": ". A one-way feedback/bug-report channel to Haven for a signed-in user and the agent working in their terminal — needs ",
            "code": false
          },
          {
            "text": "haven login",
            "code": true
          },
          {
            "text": ", 4000 characters (code points) or fewer, several unquoted words are joined into one text like ",
            "code": false
          },
          {
            "text": "contacts add",
            "code": true
          },
          {
            "text": "'s own free-text argument.",
            "code": false
          }
        ],
        "action_required": false
      }
    ]
  }
}
