/**
 * Client releases — what a published Haven client needs to know about
 * releases, as data (#3304, epic #3302 slice 2).
 *
 * Two public documents serve this: the backend's `GET /discovery`
 * (`client_releases`) and the frontend's `/.well-known/haven.json` (its
 * `packages` entries), plus the human-readable page at
 * {@link RELEASE_NOTES_PATH}. All three are built by {@link buildReleaseCompat},
 * and the version thresholds come from `CLIENT_COMPAT` in `client-compat.ts`,
 * the table the backend ENFORCES (the epic's "a published minimum is a
 * promise" note). One caveat: the frontend and the backend deploy — and roll
 * back — separately, each with its own bundled copy of this package. So the
 * frontend prefers the thresholds the reachable backend reports in
 * `/discovery`, and falls back to its own copy only when the backend is down.
 *
 * ## Who writes {@link CLIENT_RELEASES}
 *
 * `npm run release:bump` (#3305), from the package CHANGELOGs, into
 * `client-releases.data.ts`; it refuses to run when that file has been
 * hand-edited. It never writes `CLIENT_COMPAT` — a release must not raise a
 * minimum as a side effect.
 *
 * ## `released_version`, not `latest`
 *
 * The version recorded is the one RELEASED IN SOURCE — the version the bump
 * stamped. npm publishing happens later, on the `dev → main` promotion, and a
 * promotion can be half green (published, `latest` unmoved). Nothing here
 * reads npm, so the field is named for what it is rather than claiming npm's
 * `latest` dist-tag (#3305's scope note; `CLAUDE.md` § Releasing).
 *
 * Pure, like the rest of `@haven_ai/core`: no I/O, no environment.
 */

import {
  CLIENT_COMPAT,
  PUBLISHED_CLIENT_PACKAGES,
  type ClientCompatEntry,
  type PublishedClientPackage,
} from './client-compat.js'
import { CLIENT_RELEASES } from './client-releases.data.js'

/**
 * The public page that says what changed and whether to update. A PATH on the
 * dashboard origin: the frontend manifest serves it relative (its own-origin
 * rule), the backend resolves it against its configured frontend URL.
 */
export const RELEASE_NOTES_PATH = '/releases'

export interface ClientReleaseNote {
  version: string
  /** ISO date, `YYYY-MM-DD`. */
  date: string
  /** One or two sentences — what changed, for someone deciding whether to update. Not the CHANGELOG. */
  summary: string
  /**
   * True when a client must update to keep paying. Not the same as a breaking
   * change: BREAKING means "updating may break you", this means "not updating
   * will" (its CHANGELOG marker is `**Update required**`, never `**BREAKING**`).
   */
  action_required: boolean
}

export interface ClientRelease {
  /** The newest version released in source (see the file comment: not npm's `latest`). */
  released_version: string
  /** Newest first. */
  notes: readonly ClientReleaseNote[]
}

/**
 * Generated by the release bump from the five package CHANGELOGs (#3305) —
 * see `client-releases.data.ts`, which says how to change it (not by hand).
 * Newest note first.
 */
export { CLIENT_RELEASES }

/**
 * The command that updates `pkg` on the given connector channel (the npm
 * dist-tag a deployment hands out). Moved here from the backend's
 * `client-compat` middleware (#3303) so the update hint and the public release
 * documents print one command, not two copies.
 */
export function upgradeCommandFor(pkg: PublishedClientPackage, channel: string): string {
  switch (pkg) {
    case '@haven_ai/sdk':
      return `npm install @haven_ai/sdk@${channel}`
    case '@haven_ai/cli':
      return `npx -y @haven_ai/cli@${channel}`
    // The signer and the local MCP runtime are installed BY the connector; a
    // connector re-run reinstalls the pinned runtime (the signer's own
    // version-mismatch guidance says the same).
    case '@haven_ai/signer':
    case '@haven_ai/mcp':
    case '@haven_ai/connect':
      return `npx -y @haven_ai/connect@${channel}`
  }
}

/** One package's entry in the public release documents. */
export interface PackageReleaseCompat {
  released_version: string
  /** From `CLIENT_COMPAT`: below this, responses carry a non-blocking update hint. */
  recommended_version: string | null
  /** From `CLIENT_COMPAT`: below this, the package's refusal points answer `client_outdated`. */
  min_version: string | null
  /** Null when the caller does not know the deployment's channel (e.g. the backend was unreachable). */
  upgrade_command: string | null
  notes: readonly ClientReleaseNote[]
}

export interface BuildReleaseCompatOptions {
  releases?: Readonly<Record<PublishedClientPackage, ClientRelease>>
  compat?: Readonly<Record<PublishedClientPackage, ClientCompatEntry>>
}

/**
 * The per-package release data both public documents serve. `channel` is the
 * deployment's connector channel, or null when unknown. The tables are read
 * at CALL time, never captured at import, so the documents follow the source.
 */
export function buildReleaseCompat(
  channel: string | null,
  { releases = CLIENT_RELEASES, compat = CLIENT_COMPAT }: BuildReleaseCompatOptions = {},
): Record<PublishedClientPackage, PackageReleaseCompat> {
  const out = {} as Record<PublishedClientPackage, PackageReleaseCompat>
  for (const pkg of PUBLISHED_CLIENT_PACKAGES) {
    out[pkg] = {
      released_version: releases[pkg].released_version,
      recommended_version: compat[pkg].recommended_version,
      min_version: compat[pkg].min_version,
      upgrade_command: channel ? upgradeCommandFor(pkg, channel) : null,
      notes: releases[pkg].notes,
    }
  }
  return out
}
