import type { PoolClient } from 'pg'

export const version = '017_agent_connection_setups'

/**
 * Pending Connect Agent 2 setup state.
 *
 * The backend stores only setup-token hashes, public signing addresses, proof
 * signatures, API-key hashes, and metadata. The agent private key and plaintext
 * API key are generated by the local connector and must never be sent to or
 * stored by Haven.
 */
export async function up(client: PoolClient): Promise<void> {
  await client.query(`
    CREATE TABLE IF NOT EXISTS agent_connection_setups (
      id                    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      user_id               UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      agent_id              UUID REFERENCES agents(id) ON DELETE SET NULL,
      safe_id               UUID NOT NULL REFERENCES user_safes(id) ON DELETE CASCADE,
      name                  VARCHAR(255) NOT NULL,
      description           TEXT,
      runtime               VARCHAR(80),
      status                VARCHAR(40) NOT NULL DEFAULT 'awaiting_connection',
      setup_token_hash      VARCHAR(64) NOT NULL UNIQUE,
      setup_token_prefix    VARCHAR(32) NOT NULL,
      setup_token_expires_at TIMESTAMPTZ NOT NULL,
      setup_token_consumed_at TIMESTAMPTZ,
      challenge_id          UUID NOT NULL,
      challenge_message     TEXT NOT NULL,
      challenge_expires_at  TIMESTAMPTZ NOT NULL,
      delegate_address      VARCHAR(42),
      proof_signature       TEXT,
      api_key_prefix        VARCHAR(12),
      connector_version     VARCHAR(80),
      connector_context     JSONB NOT NULL DEFAULT '{}'::jsonb,
      install_status        JSONB NOT NULL DEFAULT '{}'::jsonb,
      approval_status       VARCHAR(40) NOT NULL DEFAULT 'not_started',
      safe_tx_hash          VARCHAR(66),
      tx_hash               VARCHAR(66),
      failure_reason        TEXT,
      created_at            TIMESTAMPTZ DEFAULT NOW(),
      updated_at            TIMESTAMPTZ DEFAULT NOW()
    );

    CREATE INDEX IF NOT EXISTS idx_agent_connection_setups_user
      ON agent_connection_setups(user_id, created_at DESC);
    CREATE INDEX IF NOT EXISTS idx_agent_connection_setups_token_hash
      ON agent_connection_setups(setup_token_hash);
    CREATE INDEX IF NOT EXISTS idx_agent_connection_setups_agent
      ON agent_connection_setups(agent_id);
	    CREATE INDEX IF NOT EXISTS idx_agent_connection_setups_status
	      ON agent_connection_setups(status);

	    CREATE UNIQUE INDEX IF NOT EXISTS idx_agents_user_delegate_non_revoked_unique
	      ON agents(user_id, lower(delegate_address))
	      WHERE delegate_address IS NOT NULL AND status != 'revoked';

	    CREATE TABLE IF NOT EXISTS agent_connection_setup_allowances (
      id                 UUID PRIMARY KEY DEFAULT gen_random_uuid(),
      setup_id           UUID NOT NULL REFERENCES agent_connection_setups(id) ON DELETE CASCADE,
      token_address      VARCHAR(42) NOT NULL,
      token_symbol       VARCHAR(20) NOT NULL,
      allowance_amount   VARCHAR(78) NOT NULL,
      reset_period_min   INTEGER NOT NULL DEFAULT 0,
      created_at         TIMESTAMPTZ DEFAULT NOW(),
      updated_at         TIMESTAMPTZ DEFAULT NOW(),
      UNIQUE(setup_id, token_address)
    );

    CREATE INDEX IF NOT EXISTS idx_agent_connection_setup_allowances_setup
      ON agent_connection_setup_allowances(setup_id);
  `)
}
