/**
 * Browser-side half of the transaction CSV export (#2871).
 *
 * The file itself is generated by the backend — `GET /transactions/export.csv`
 * — because only the server sees the whole filtered result set; this module
 * used to build the CSV from whatever page the table had loaded. What is left
 * here is the download shim.
 */

/**
 * Trigger a download of `csv` under `filename`.
 *
 * The body already carries the backend's UTF-8 BOM, so nothing is prepended
 * here: doing it twice writes a stray BOM into the first header cell.
 */
export function downloadCsv(csv: string, filename: string): void {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' })
  const url = URL.createObjectURL(blob)
  const anchor = document.createElement('a')
  anchor.href = url
  anchor.download = filename
  anchor.click()
  URL.revokeObjectURL(url)
}

/**
 * Filename for a downloaded export. The backend sends one in
 * `Content-Disposition`, but `fetch` + `Blob` does not honour that header —
 * the download is driven by the anchor's `download` attribute — so the same
 * `haven-transactions-YYYYMMDD.csv` shape is built here. UTC, matching
 * `buildTransactionCsvFilename` on the backend.
 */
export function buildCsvFilename(now: Date): string {
  const pad = (n: number) => String(n).padStart(2, '0')
  const stamp = `${now.getUTCFullYear()}${pad(now.getUTCMonth() + 1)}${pad(now.getUTCDate())}`
  return `haven-transactions-${stamp}.csv`
}
